### PR TITLE
spectre-meltdown-checker: Update to 0.42

### PR DESCRIPTION
**Pull request by iwamatsu**
Signed-off-by: Nobuhiro Iwamatsu <nobuhiro1.iwamatsu@toshiba.co.jp>

### CODE REVIEW

**Comment by mwasilew** [comment]
@nareshkamboju, @mrchapp, could you review this. It looks OK to me but you're main users on our side.

**Comment by nareshkamboju** [comment]
@iwamatsu with new version 0.42 any change is output log ?
Because our script expect the output pattern to parse the verdict.

If you have tested 0.42 please share log here.

However, I will test 0.42 version and let you know.

**Comment by nareshkamboju** [comment]
Tested 0.42 version on arm64 and x86_64 and test run to complete.
Total test count increased by 4.

https://lkft.validation.linaro.org/results/900048/2_spectre-meltdown-checker-test
https://lkft.validation.linaro.org/results/900058/2_spectre-meltdown-checker-test

OTOH, I will submit a patch to update pre downloaded test scripts inside ./bin directory.

- Naresh

**Comment by mwasilew** [comment]
Thanks Naresh!

**Pull request merged**
