### PR TITLE
automated: kselftest: update parser

### PR DESCRIPTION
**Pull request by roxell**
Update to use the same parser that 'kunit' uses.

Since there are a lot of subtests in kselftest that produce the same output like 'clone3 438_result_22_matches_expectation_22' thats why the subtest number are included into the test name.
The subsuite tests in 'kunit' are uniq, thats why we don't need to include the subtest number.

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>

### CODE REVIEW

**Comment by gctucker** [comment]
OOI is this changing the names of the individual test cases as reported to LAVA?

**Comment by nareshkamboju** [comment]
@gctucker 
New names are more detailed and more number of test cases
For example selftests: clone3 in the old way we captured 5 test cases new ways gets 54 test cases.
For more details please refer below links,

e.g.
Old name:   clone3.clone3
New name:  clone3_1_selftests_clone3_clone3

Old LAVA job: only 5 test cases

clone3.clone3
clone3.clone3_clear_sighand
clone3.clone3_set_tid
clone3.clone3_cap_checkpoint_restore.global.clone3_cap_checkpoint_restore
clone3.clone3_cap_checkpoint_restore

- https://lkft.validation.linaro.org/results/5928297/5_kselftest-clone3


New LAVA job: 54 test cases with more details

clone3_1_514_Result_0_matches_expectation_0
clone3_2_514_Result_0_matches_expectation_0
clone3_3_514_Result_0_matches_expectation_0
clone3_4_514_Result_22_matches_expectation_22
clone3_5_514_Result_0_matches_expectation_0
clone3_6_514_Result_22_matches_expectation_22
clone3_7_514_Result_22_matches_expectation_22
clone3_8_514_Result_22_matches_expectation_22
clone3_9_514_Result_22_matches_expectation_22
clone3_10_514_Result_0_matches_expectation_0
clone3_11_514_Result_7_matches_expectation_7
clone3_12_514_Result_7_matches_expectation_7
clone3_13_514_Result_7_matches_expectation_7
clone3_14_514_Result_0_matches_expectation_0
clone3_15_514_Result_22_matches_expectation_22
clone3_16_514_Result_0_matches_expectation_0
clone3_17_514_Result_7_matches_expectation_7
clone3_1_selftests_clone3_clone3
clone3_1_Cleared_signal_handlers_for_child_process
clone3_2_selftests_clone3_clone3_clear_sighand
clone3_1_556_Result_22_matches_expectation_22
clone3_2_556_Result_22_matches_expectation_22
clone3_3_556_Result_22_matches_expectation_22
clone3_4_556_Result_22_matches_expectation_22
clone3_5_556_Result_22_matches_expectation_22
clone3_6_556_Result_22_matches_expectation_22
clone3_7_556_Result_22_matches_expectation_22
clone3_8_556_Result_22_matches_expectation_22
clone3_9_556_Result_22_matches_expectation_22
clone3_10_556_Result_22_matches_expectation_22
clone3_11_556_Result_22_matches_expectation_22
clone3_12_556_Result_22_matches_expectation_22
clone3_13_556_Result_22_matches_expectation_22
clone3_14_556_Result_22_matches_expectation_22
clone3_15_556_Result_17_matches_expectation_17
clone3_16_556_Result_0_matches_expectation_0
clone3_17_556_Result_22_matches_expectation_22
clone3_18_556_Result_22_matches_expectation_22
clone3_18_556_Result_22_matches_expectation_22
clone3_19_556_Result_0_matches_expectation_0
clone3_20_556_Result_22_matches_expectation_22
clone3_21_556_Result_0_matches_expectation_0
clone3_22_556_Result_22_matches_expectation_22
clone3_23_1_Result_22_matches_expectation_22
clone3_24_1_Result_0_matches_expectation_0
clone3_25_1_Result_0_matches_expectation_0
clone3_26_1_Result_22_matches_expectation_22
clone3_27_1_Result_22_matches_expectation_22
clone3_28_1_Result_0_matches_expectation_0
clone3_22_556_Result_22_matches_expectation_22
clone3_29_PIDs_in_all_namespaces_as_expected_558_42_1
clone3_3_selftests_clone3_clone3_set_tid
clone3_1_global_clone3_cap_checkpoint_restore
clone3_4_selftests_clone3_clone3_cap_checkpoint_restore

- https://lkft.validation.linaro.org/results/5939374/2_kselftest-arm64?search=&length=100&sort=result#table

**Comment by gctucker** [comment]
OK so the test names are changing, which will reset all the regression tracking in KernelCI.  Good to know ;)

**Comment by nareshkamboju** [comment]
@gctucker gctucker


Summary:
---------------
This results parser script will parse test results in more accurate way,
  1. Detailed test names
  2.  Testname_sub_testnmae 
  3. Testname_with_test_number_sub_testname
  4.  Testname_with_test_number_sub_testname_expected_results_vs_test_results
  
I have listed out new LAVA results in the bottom,

old set of results:
--------------------
core.close_range_test.global.core_close_range
core.close_range_test.global.close_range_unshare
core.close_range_test.global.close_range_unshare_capped
core.close_range_test.global.close_range_cloexec
core.close_range_test.global.close_range_cloexec_unshare
core.close_range_test.global.close_range_cloexec_syzbot
core.close_range_test.global.close_range_cloexec_unshare_syzbot
core.close_range_test


New set of results:
--------------------
core_close_range_test_1_global_core_close_range
core_close_range_test_2_global_close_range_unshare
core_close_range_test_3_global_close_range_unshare_capped
core_close_range_test_4_global_close_range_cloexec
core_close_range_test_5_global_close_range_cloexec_unshare
core_close_range_test_6_global_close_range_cloexec_syzbot
core_close_range_test_7_global_close_range_cloexec_unshare_syzbot
core_close_range_test


old set of results:
--------------------
capabilities.test_execve.Passed
capabilities.test_execve.PR_CAP_AMBIENT_RAISE
capabilities.test_execve.PR_CAP_AMBIENT_RAISE
capabilities.test_execve.PR_CAP_AMBIENT_RAISE
capabilities.test_execve.Basic
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve.PR_CAP_AMBIENT_RAISE
capabilities.test_execve.PR_CAP_AMBIENT_RAISE
capabilities.test_execve.PR_CAP_AMBIENT_RAISE
capabilities.test_execve.Basic
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve.Passed
capabilities.test_execve



New set of results:
--------------------
capabilities_test_execve_1_Passed
capabilities_test_execve_2_PR_CAP_AMBIENT_RAISE_failed_on_non-inheritable_cap
capabilities_test_execve_3_PR_CAP_AMBIENT_RAISE_failed_on_non-permitted_cap
capabilities_test_execve_4_PR_CAP_AMBIENT_RAISE_worked
capabilities_test_execve_5_Basic_manipulation_appears_to_work
capabilities_test_execve_6_Passed
capabilities_test_execve_7_Passed
capabilities_test_execve_8_Passed
capabilities_test_execve_9_Passed
capabilities_test_execve_10_Passed
capabilities_test_execve_11_Passed
capabilities_test_execve_12_Passed
capabilities_test_execve_1_Passed
capabilities_test_execve_2_PR_CAP_AMBIENT_RAISE_failed_on_non-inheritable_cap
capabilities_test_execve_3_PR_CAP_AMBIENT_RAISE_failed_on_non-permitted_cap
capabilities_test_execve_4_PR_CAP_AMBIENT_RAISE_worked
capabilities_test_execve_5_Basic_manipulation_appears_to_work
capabilities_test_execve_6_Passed
capabilities_test_execve_7_Passed
capabilities_test_execve_8_Passed
capabilities_test_execve_9_Passed
capabilities_test_execve

old set of results:
--------------------
membarrier.membarrier_test_single_thread.sys_membarrier
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread.sys
membarrier.membarrier_test_single_thread
membarrier.membarrier_test_multi_thread.sys_membarrier
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread.sys
membarrier.membarrier_test_multi_thread



New set of results:
--------------------
membarrier_membarrier_test_single_thread_1_sys_membarrier_available
membarrier_membarrier_test_single_thread_2_sys_membarrier_invalid_command_test_command_1_flags_0_errno_22_Failed_as_expected
membarrier_membarrier_test_single_thread_3_sys_membarrier_MEMBARRIER_CMD_QUERY_invalid_flags_test_flags_1_errno_22_Failed_as_expected
membarrier_membarrier_test_single_thread_4_sys_membarrier_MEMBARRIER_CMD_PRIVATE_EXPEDITED_not_registered_failure_test_flags_0_errno_1
membarrier_membarrier_test_single_thread_5_sys_membarrier_MEMBARRIER_CMD_PRIVATE_EXPEDITED_SYNC_CORE_not_registered_failure_test_flags_0_errno_1
membarrier_membarrier_test_single_thread_6_sys_membarrier_MEMBARRIER_CMD_GLOBAL_test_flags_0
membarrier_membarrier_test_single_thread_7_sys_membarrier_MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED_test_flags_0
membarrier_membarrier_test_single_thread_8_sys_membarrier_MEMBARRIER_CMD_PRIVATE_EXPEDITED_test_flags_0
membarrier_membarrier_test_single_thread_9_sys_membarrier_MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED_SYNC_CORE_test_flags_0
membarrier_membarrier_test_single_thread_10_sys_membarrier_MEMBARRIER_CMD_PRIVATE_EXPEDITED_SYNC_CORE_test_flags_0
membarrier_membarrier_test_single_thread_11_sys_membarrier_MEMBARRIER_CMD_GLOBAL_EXPEDITED_test_flags_0
membarrier_membarrier_test_single_thread_12_sys_membarrier_MEMBARRIER_CMD_REGISTER_GLOBAL_EXPEDITED_test_flags_0
membarrier_membarrier_test_single_thread_13_sys_membarrier_MEMBARRIER_CMD_GLOBAL_EXPEDITED_test_flags_0
membarrier_membarrier_test_single_thread
membarrier_membarrier_test_multi_thread_1_sys_membarrier_available
membarrier_membarrier_test_multi_thread_2_sys_membarrier_invalid_command_test_command_1_flags_0_errno_22_Failed_as_expected
membarrier_membarrier_test_multi_thread_3_sys_membarrier_MEMBARRIER_CMD_QUERY_invalid_flags_test_flags_1_errno_22_Failed_as_expected
membarrier_membarrier_test_multi_thread_4_sys_membarrier_MEMBARRIER_CMD_PRIVATE_EXPEDITED_not_registered_failure_test_flags_0_errno_1
membarrier_membarrier_test_multi_thread_5_sys_membarrier_MEMBARRIER_CMD_PRIVATE_EXPEDITED_SYNC_CORE_not_registered_failure_test_flags_0_errno_1
membarrier_membarrier_test_multi_thread_6_sys_membarrier_MEMBARRIER_CMD_GLOBAL_test_flags_0
membarrier_membarrier_test_multi_thread_7_sys_membarrier_MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED_test_flags_0
membarrier_membarrier_test_multi_thread_8_sys_membarrier_MEMBARRIER_CMD_PRIVATE_EXPEDITED_test_flags_0
membarrier_membarrier_test_multi_thread_9_sys_membarrier_MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED_SYNC_CORE_test_flags_0
membarrier_membarrier_test_multi_thread_10_sys_membarrier_MEMBARRIER_CMD_PRIVATE_EXPEDITED_SYNC_CORE_test_flags_0
membarrier_membarrier_test_multi_thread_11_sys_membarrier_MEMBARRIER_CMD_GLOBAL_EXPEDITED_test_flags_0
membarrier_membarrier_test_multi_thread_12_sys_membarrier_MEMBARRIER_CMD_REGISTER_GLOBAL_EXPEDITED_test_flags_0
membarrier_membarrier_test_multi_thread_13_sys_membarrier_MEMBARRIER_CMD_GLOBAL_EXPEDITED_test_flags_0
membarrier_membarrier_test_multi_thread

old set of results:
--------------------
arm64.tags_test
arm64.run_tags_test.sh
arm64.fake_sigreturn_bad_magic
arm64.fake_sigreturn_bad_size
arm64.fake_sigreturn_bad_size_for_magic0
arm64.fake_sigreturn_duplicated_fpsimd
arm64.fake_sigreturn_misaligned_sp
arm64.fake_sigreturn_missing_fpsimd
arm64.fake_sigreturn_sme_change_vl
arm64.fake_sigreturn_sve_change_vl
arm64.mangle_pstate_invalid_compat_toggle
arm64.mangle_pstate_invalid_daif_bits
arm64.mangle_pstate_invalid_mode_el1h
arm64.mangle_pstate_invalid_mode_el1t
arm64.mangle_pstate_invalid_mode_el2h
arm64.mangle_pstate_invalid_mode_el2t
arm64.mangle_pstate_invalid_mode_el3h
arm64.mangle_pstate_invalid_mode_el3t
arm64.sme_trap_non_streaming
arm64.sme_trap_no_sm
arm64.sme_trap_za
arm64.sme_vl
arm64.ssve_regs
arm64.sve_regs
arm64.sve_vl
arm64.za_no_regs
arm64.za_regs
arm64.pac
arm64.fp-stress.FPSIMD-0-0
arm64.fp-stress.FPSIMD-0-1
and more

New set of results:
--------------------
arm64_tags_test
arm64_run_tags_test_sh
arm64_fake_sigreturn_bad_magic
arm64_fake_sigreturn_bad_size
arm64_fake_sigreturn_bad_size_for_magic0
arm64_fake_sigreturn_duplicated_fpsimd
arm64_fake_sigreturn_misaligned_sp
arm64_fake_sigreturn_missing_fpsimd
arm64_fake_sigreturn_sme_change_vl
arm64_fake_sigreturn_sve_change_vl
arm64_mangle_pstate_invalid_compat_toggle
arm64_mangle_pstate_invalid_daif_bits
arm64_mangle_pstate_invalid_mode_el1h
arm64_mangle_pstate_invalid_mode_el1t
arm64_mangle_pstate_invalid_mode_el2h
arm64_mangle_pstate_invalid_mode_el2t
arm64_mangle_pstate_invalid_mode_el3h
arm64_mangle_pstate_invalid_mode_el3t
arm64_sme_trap_non_streaming
arm64_sme_trap_no_sm
arm64_sme_trap_za
arm64_sme_vl
arm64_ssve_regs
arm64_sve_regs
arm64_sve_vl
arm64_za_regs
arm64_pac_1_global_corrupt_pac
arm64_pac_2_global_pac_instructions_not_nop
arm64_pac_3_global_pac_instructions_not_nop_generic
arm64_pac_4_global_single_thread_different_keys
arm64_pac_5_global_exec_changed_keys
arm64_pac_6_global_context_switch_keep_keys
arm64_pac_7_global_context_switch_keep_keys_generic
arm64_pac
arm64_sve-ptrace_1_SVE_FPSIMD_set_via_SVE_0
arm64_sve-ptrace_2_SVE_get_fpsimd_gave_same_state
arm64_sve-ptrace_3_SVE_SVE_PT_VL_INHERIT_set
arm64_sve-ptrace_4_SVE_SVE_PT_VL_INHERIT_cleared
arm64_sve-ptrace_5_Set_SVE_VL_16
arm64_sve-ptrace_6_Set_and_get_SVE_data_for_VL_16
arm64_sve-ptrace_7_Set_and_get_FPSIMD_data_for_SVE_VL_16
arm64_sve-ptrace_8_Set_FPSIMD_read_via_SVE_for_SVE_VL_16
arm64_sve-ptrace_9_Set_SVE_VL_32
arm64_sve-ptrace_10_Set_and_get_SVE_data_for_VL_32
arm64_sve-ptrace_11_Set_and_get_FPSIMD_data_for_SVE_VL_32
arm64_sve-ptrace_12_Set_FPSIMD_read_via_SVE_for_SVE_VL_32
arm64_sve-ptrace_13_Set_SVE_VL_48
arm64_sve-ptrace_14_Set_and_get_SVE_data_for_VL_48
arm64_sve-ptrace_15_Set_and_get_FPSIMD_data_for_SVE_VL_48
arm64_sve-ptrace_16_Set_FPSIMD_read_via_SVE_for_SVE_VL_48
and more

New set of kselftest results LAVA jobs,
----------------------------------------
https://lkft.validation.linaro.org/results/5985367
https://lkft.validation.linaro.org/results/5985368
https://lkft.validation.linaro.org/results/5985369
https://lkft.validation.linaro.org/results/5985370
https://lkft.validation.linaro.org/results/5985371
https://lkft.validation.linaro.org/results/5985372
https://lkft.validation.linaro.org/results/5985373
https://lkft.validation.linaro.org/results/5985374
https://lkft.validation.linaro.org/results/5985375
https://lkft.validation.linaro.org/results/5985376
https://lkft.validation.linaro.org/results/5985377
https://lkft.validation.linaro.org/results/5985378
https://lkft.validation.linaro.org/results/5985379
https://lkft.validation.linaro.org/results/5985380
https://lkft.validation.linaro.org/results/5985381
https://lkft.validation.linaro.org/results/5985382
https://lkft.validation.linaro.org/results/5985383
https://lkft.validation.linaro.org/results/5985384
https://lkft.validation.linaro.org/results/5985385
https://lkft.validation.linaro.org/results/5985386
https://lkft.validation.linaro.org/results/5985387
https://lkft.validation.linaro.org/results/5985388
https://lkft.validation.linaro.org/results/5985389
https://lkft.validation.linaro.org/results/5985390
https://lkft.validation.linaro.org/results/5985391
https://lkft.validation.linaro.org/results/5985392
https://lkft.validation.linaro.org/results/5985393
https://lkft.validation.linaro.org/results/5985394
https://lkft.validation.linaro.org/results/5985395
https://lkft.validation.linaro.org/results/5985396
https://lkft.validation.linaro.org/results/5985397
https://lkft.validation.linaro.org/results/5985398
https://lkft.validation.linaro.org/results/5985399
https://lkft.validation.linaro.org/results/5985400

**Pull request merged**
