### PR TITLE
automated: linux: fix issues with static-delta OTA update

### PR DESCRIPTION
**Pull request by mwasilew**
When updating the device using static deltas, the test script has to wait for aktualizr-lite to complete installation before rebooting.

When there is no static detla available, the test job should end as incomplete.

This patch also changes how the aklite signal is checked to align with other OTA testing scripts.

### CODE REVIEW

**Comment by roxell** [comment]
Can we not use tabs when indenting, this file is indented with space.

**Comment by mwasilew** [comment]
Hmm, I didn't change the indentation. I checked a few other scripts and all are using spaces. Are you sure you want to change it?

**Comment by roxell** [comment]
> Hmm, I didn't change the indentation. I checked a few other scripts and all are using spaces. Are you sure you want to change it?

hmm, I'm sorry my comment didn't make sense. What I meant was that you have added tabs in this PR, and the script uses spaces.

**Comment by mwasilew** [comment]
Now it makes sense. Fixed.

**Pull request merged**
