### PR TITLE
spectre-meltdown-checker: Update to 0.44

### PR DESCRIPTION
**Pull request by aliceinwire**
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>

### CODE REVIEW

**Comment by roxell** [comment]
Thank you for the contribution. Can you please update the changelog explaining whats the updates between release 0.42 and 0.44.

**Comment by nareshkamboju** [comment]
@aliceinwire just share the link for the repo and release notes
https://github.com/speed47/spectre-meltdown-checker/releases

**Comment by nareshkamboju** [comment]
@aliceinwire This patch looks good.
Please update your commit message by adding this url
https://github.com/speed47/spectre-meltdown-checker/releases

**Comment by aliceinwire** [comment]
> @aliceinwire This patch looks good. Please update your commit message by adding this url https://github.com/speed47/spectre-meltdown-checker/releases

ok

**Comment by aliceinwire** [comment]
@roxell updated

**Comment by nareshkamboju** [comment]
@aliceinwire Thanks for your patch.

**Comment by roxell** [comment]
Thanks @aliceinwire LGTM.

**Pull request merged**
