### PR TITLE
automated: linux: Add AWS IoT use case to el2go test

### PR DESCRIPTION
**Pull request by mwasilew**
This patch adds support for testing AWS IoT integration for EL2GO service with FoundriesFactory. More detailed instructions are available from the el2go.yaml

### CODE REVIEW

**Comment by mwasilew** [comment]
It's set in /etc/os-release. This is the FoundriesFactory name for the build.

**Comment by mwasilew** [comment]
I added a comment in the shell script to clarify the situation

**Review by nareshkamboju — CHANGES_REQUESTED** [review]
Since check returns is checking.
then no problem.

+ #echo "Cleanup SE050"
you may remove this line.
or
keep it.
 echo "Cleanup SE050"

**Comment by mwasilew** [comment]
Fixed.

**Pull request merged**
