### PR TITLE
automated: linux: fwts: filter out x86 tests on other archs

### PR DESCRIPTION
**Pull request by roxell**
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>

### CODE REVIEW

**Comment by nareshkamboju** [comment]
There are long list of unsupported / unavailable tests on arm64.
I would like to opt for default test runs - which means  the parameter TESTS: ' ' to be passed from lava test plans.

**Comment by mwasilew** [comment]
@roxell Could you add a comment with the list of possible tests?

**Comment by roxell** [comment]
@mwasilew thats decided by the test suite. since its a lot of arch dependent tests the testsuite can and should decide which tests to run.

**Comment by nareshkamboju** [comment]
Thanks for the patch.
Lets test suite decide what list of tests it should run.

x86_64 running 1500 Tests
arm64 running 17 tests.

However, I like the default test run by fwts.

+1

**Review by nareshkamboju — APPROVED** [review]

**Pull request merged**
