### PR TITLE
Added test definition to drive ion-monitor-tool for Android.

### PR DESCRIPTION
**Pull request by axelnxp**
Also added an example test job for LAVA.
This tool comes from MMWG team, to help monitoring memory leaks with ION heaps.

Signed-off-by: Axel Le Bourhis <axel.lebourhis@nxp.com>

### CODE REVIEW

**Comment by axelnxp** [comment]
I would like to add Peter Griffin and Arthur She as reviewers of the pull request, but I don't know if I can ?

**Comment by mwasilew** [comment]
@axelnxp here is the output from shellcheck:
```
* SHELLCHECK: [FAILED]: automated/android/ion-monitor-tool/runner.sh
* SHELLCHECK: [OUTPUT]:
 
 In automated/android/ion-monitor-tool/runner.sh line 13:
 case "${option}"
 ^-- SC2220: Invalid flags are not handled. Add a *) case.
 
 
 In automated/android/ion-monitor-tool/runner.sh line 40:
 cat ./stdout.log | grep RESULT | awk '{print $2" "$3""}' | sed "s/FAIL/fail/; s/PASS/pass/" > results.txt
     ^----------^ SC2002: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.
 
 
 In automated/android/ion-monitor-tool/runner.sh line 41:
 while read line
       ^--^ SC2162: read without -r will mangle backslashes.
 
 
 In automated/android/ion-monitor-tool/runner.sh line 43:
     TEST_CASE=$(echo ${line} | awk '{print $1}')
                      ^-----^ SC2086: Double quote to prevent globbing and word splitting.
 
 
 In automated/android/ion-monitor-tool/runner.sh line 44:
     RESULT=$(echo ${line} | awk '{print $2}')
                   ^-----^ SC2086: Double quote to prevent globbing and word splitting.
 
 For more information:
   https://www.shellcheck.net/wiki/SC2220 -- Invalid flags are not handled. Ad...
   https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
   https://www.shellcheck.net/wiki/SC2162 -- read without -r will mangle backs...
* SHELLCHECK: [PASSED]: automated/android/ion-monitor-tool/setup.sh
```

**Comment by mwasilew** [comment]
@petegriffin @arthur-she could you take a look at this patch?

**Comment by axelnxp** [comment]
@mwasilew I fixed the errors reported by shellcheck, and updated the PR.
Just a question, the shellcheck I use didn't report SC2220 and SC2162.
Do you know why ? I'm using Ubuntu 16.04

**Comment by mwasilew** [comment]
@axelnxp most likely old version of shellcheck. Travis says it uses shellcheck version 0.6.0

**Comment by axelnxp** [comment]
@mwasilew Yeah ok default package from Ubuntu repo is 0.3.x, I updated to 0.6.0 :)

**Pull request merged**
