### PR TITLE
meminfo: add new test

### PR DESCRIPTION
**Pull request by omnium21**
Add a new test based on automated/android/meminfo,
but remove the Android specific parts.

Signed-off-by: Ryan Harkin <ryan.harkin@linaro.org>

### CODE REVIEW

**Comment by omnium21** [comment]
Here's a test job where I ran this test:
https://validation.linaro.org/scheduler/job/1933736

**Comment by mwasilew** [comment]
Shellcheck complains about the 'cat':
```
In automated/linux/meminfo/meminfo.sh line 13:
cat /proc/meminfo 2>&1 | tee "${OUTPUT}/proc-meminfo"
     ^-----------^ SC2002: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.
```

**Comment by mwasilew** [comment]
I guess in this case shellcheck is wrong. Could you add # shellcheck disable=SC2002 before the line with cat?

**Comment by omnium21** [comment]
Thanks Milosz. I added the change and rebased to master, since the docker change was merged already.

**Pull request merged**
