### PR TITLE
sanity-check: allow to check all changes on the branch

### PR DESCRIPTION
**Pull request by mwasilew**
So far only last commit was tested automatically in travis. This patch
changes this by testing all files that were changed in the branch.

Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>

### CODE REVIEW

**Comment by danrue** [comment]
It seems really complicated, and getting worse. How much work is it to fix everything so that we can globally validate the whole repo every time?

**Comment by mwasilew** [comment]
It's a bit of work. There are a few 'non compliant' scripts :(

**Comment by danrue** [comment]
How about a list of excluded scripts and the rest are all globally checked?

**Comment by mwasilew** [comment]
I was over pessimistic it seems. Most of the issues are now fixed. I hope the scripts still work as expected. There are a few python 'try-except' problems left that I will try to address tomorrow.

**Comment by mwasilew** [comment]
@alimon, @ndechesne, @mrchapp, @chase-qi could you take a look? There are quite a few changes and I hope I didn't break anything. The goal is to make the sanity-check validate all files on each PR and push.

**Comment by mwasilew** [comment]
@nareshkamboju could you take a look?

**Comment by mrchapp** [comment]
+1 Looks good to me, but someone else must approve.

**Comment by alimon** [comment]
@mwasilew Is fine for me.

**Comment by chase-qi** [comment]
LGTM

**Comment by mwasilew** [comment]
OK, let's merge it. Please alarm if there is anything wrong with your tests/results.

**Pull request merged**
