### PR TITLE
automated/linux: add new test igt

### PR DESCRIPTION
**Pull request by arthur-she**

### CODE REVIEW

**Comment by arthur-she** [comment]
Test job
https://staging.validation.linaro.org/scheduler/job/250787

**Comment by nareshkamboju** [comment]
root@kamboju:/home/naresh/git-local/april/igt/test-definitions# . automated/bin/setenv.sh 
REPO_PATH: /home/naresh/git-local/april/igt/test-definitions
BIN_PATH: /home/naresh/git-local/april/igt/test-definitions/automated/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@kamboju:/home/naresh/git-local/april/igt/test-definitions# test-runner -d automated/linux/igt/igt-chamelium-test.yaml 
2019-04-10 13:44:45,970 - RUNNER: INFO: Tests to run:
{'path': 'automated/linux/igt/igt-chamelium-test.yaml', 'uuid': 'c55db718-ed7e-463e-b139-d0e1d47e753b', 'timeout': None, 'skip_install': False}
2019-04-10 13:44:46,058 - RUNNER.TestSetup: INFO: Test repo copied to: /root/output/igt-chamelium-test_c55db718-ed7e-463e-b139-d0e1d47e753b
2019-04-10 13:44:46,062 - RUNNER.TestRun: INFO: Executing /root/output/igt-chamelium-test_c55db718-ed7e-463e-b139-d0e1d47e753b/run.sh
+ export TESTRUN_ID=igt-chamelium-test
+ cd /root/output/igt-chamelium-test_c55db718-ed7e-463e-b139-d0e1d47e753b
+ cat uuid
+ UUID=c55db718-ed7e-463e-b139-d0e1d47e753b
+ echo <STARTRUN igt-chamelium-test c55db718-ed7e-463e-b139-d0e1d47e753b>
<STARTRUN igt-chamelium-test c55db718-ed7e-463e-b139-d0e1d47e753b>
+ export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
+ cd ./automated/linux/igt
+ git config --global http.sslverify false
+ [ -n  ]
+ ./igt-chamelium-test.sh -c 192.168.29.200 -h HDMI-A-1 -d /igt-gpu-tools
Generate ~/.igtrc
Download Piglit..
./igt-chamelium-test.sh: line 60: /igt-gpu-tools/scripts/run-tests.sh: No such file or directory
Generate test list
./igt-chamelium-test.sh: line 28: /igt-gpu-tools/scripts/run-tests.sh: No such file or directory
tee: /igt-gpu-tools/igt-chamelium-test.testlist: No such file or directory
Run igt-chamelium-test.testlist
./igt-chamelium-test.sh: line 69: /igt-gpu-tools/scripts/run-tests.sh: No such file or directory
awk: warning: escape sequence `\ ' treated as plain ` '
+ ../../utils/send-to-lava.sh result.log
+ echo <ENDRUN igt-chamelium-test c55db718-ed7e-463e-b139-d0e1d47e753b>
2019-04-10 13:44:46,113 - RUNNER.ResultParser: INFO: Result files saved to: /root/output/igt-chamelium-test_c55db718-ed7e-463e-b139-d0e1d47e753b
--- Printing result.csv ---
name,test_case_id,result,measurement,units,test_params
igt-chamelium-test,no-result-found,fail,,,CHAMELIUM_IP=192.168.29.200;HDMI_DEV_NAME=HDMI-A-1;IGT_DIR=/igt-gpu-tools;TEST_LIST=;TL=

**Comment by nareshkamboju** [comment]
@arthur-she would it be possible to run this test with out LAVA.
By using test runner we could run this locally but i see below issues.

root@kamboju:/home/naresh/git-local/april/igt/test-definitions# . automated/bin/setenv.sh 
REPO_PATH: /home/naresh/git-local/april/igt/test-definitions
BIN_PATH: /home/naresh/git-local/april/igt/test-definitions/automated/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@kamboju:/home/naresh/git-local/april/igt/test-definitions# test-runner -d automated/linux/igt/igt-chamelium-test.yaml 
2019-04-10 13:44:45,970 - RUNNER: INFO: Tests to run:
{'path': 'automated/linux/igt/igt-chamelium-test.yaml', 'uuid': 'c55db718-ed7e-463e-b139-d0e1d47e753b', 'timeout': None, 'skip_install': False}
2019-04-10 13:44:46,058 - RUNNER.TestSetup: INFO: Test repo copied to: /root/output/igt-chamelium-test_c55db718-ed7e-463e-b139-d0e1d47e753b
2019-04-10 13:44:46,062 - RUNNER.TestRun: INFO: Executing /root/output/igt-chamelium-test_c55db718-ed7e-463e-b139-d0e1d47e753b/run.sh
+ export TESTRUN_ID=igt-chamelium-test
+ cd /root/output/igt-chamelium-test_c55db718-ed7e-463e-b139-d0e1d47e753b
+ cat uuid
+ UUID=c55db718-ed7e-463e-b139-d0e1d47e753b
+ echo <STARTRUN igt-chamelium-test c55db718-ed7e-463e-b139-d0e1d47e753b>
<STARTRUN igt-chamelium-test c55db718-ed7e-463e-b139-d0e1d47e753b>
+ export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
+ cd ./automated/linux/igt
+ git config --global http.sslverify false
+ [ -n  ]
+ ./igt-chamelium-test.sh -c 192.168.29.200 -h HDMI-A-1 -d /igt-gpu-tools
Generate ~/.igtrc
Download Piglit..
./igt-chamelium-test.sh: line 60: /igt-gpu-tools/scripts/run-tests.sh: No such file or directory
Generate test list
./igt-chamelium-test.sh: line 28: /igt-gpu-tools/scripts/run-tests.sh: No such file or directory
tee: /igt-gpu-tools/igt-chamelium-test.testlist: No such file or directory
Run igt-chamelium-test.testlist
./igt-chamelium-test.sh: line 69: /igt-gpu-tools/scripts/run-tests.sh: No such file or directory
awk: warning: escape sequence `\ ' treated as plain ` '
+ ../../utils/send-to-lava.sh result.log
+ echo <ENDRUN igt-chamelium-test c55db718-ed7e-463e-b139-d0e1d47e753b>
2019-04-10 13:44:46,113 - RUNNER.ResultParser: INFO: Result files saved to: /root/output/igt-chamelium-test_c55db718-ed7e-463e-b139-d0e1d47e753b
--- Printing result.csv ---
name,test_case_id,result,measurement,units,test_params
igt-chamelium-test,no-result-found,fail,,,CHAMELIUM_IP=192.168.29.200;HDMI_DEV_NAME=HDMI-A-1;IGT_DIR=/igt-gpu-tools;TEST_LIST=;TL=

**Comment by arthur-she** [comment]
@nareshkamboju, it could be run without LAVA, indeed. However, you have to have the Chamelium, the hardware, and igt-gpu-tools, the software, in your system.
The error shows the igt-gpu-tools cannot be found in the directory "/igt-gpu-tools"

**Pull request merged**
